# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('cupo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.Grado')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='profe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.Profesor'),
        ),
        migrations.AddField(
            model_name='grado',
            name='porfesores',
            field=models.ManyToManyField(through='profesor.Materia', to='profesor.Profesor'),
        ),
    ]
